### Healthcheck
GET http://127.0.0.1:5000/

### detect grid
PUT http://127.0.0.1:5000/detect-grid
Content-Type: image/jpeg

< input/gow1.jpeg

### detect balls
PUT http://127.0.0.1:5000/upload?x=415&y=44&grid_size=507
Content-Type: image/jpeg

< input/gow1.jpeg

